# Generated by Django 4.0.4 on 2023-05-07 07:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='application_files/', validators=[api.models.validate_file_size]),
        ),
    ]
