# Generated by Django 4.0.4 on 2023-05-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blocker_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.blocker'),
        ),
    ]
