name: milsat_project_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+6

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.0
  flutter: 
    sdk: flutter
  flutter_riverpod: ^2.3.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  introduction_screen: ^3.1.7
  jwt_decoder: ^2.0.1
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.0.4
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/


