name: milsat_project_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+7

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  jwt_decoder: ^2.0.1
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_slidable: ^3.1.1
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/app_logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
