# Generated by Django 4.0.4 on 2023-05-07 08:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applications_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_link',
            field=models.URLField(default='https://milsat.africa'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='applications',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=api.models.unique_application_filename, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=api.models.unique_todo_filename),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.unique_profile_picture),
        ),
    ]
