# Generated by Django 4.0.4 on 2023-05-07 10:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_applications_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.unique_application_filename, validators=[api.models.validate_file_size]),
        ),
    ]
