# Generated by Django 4.0.4 on 2023-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_blocker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='purpose',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='applications',
            name='reason',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='applications',
            name='referral',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applications',
            name='skills',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='task_id_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='task_id_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='mentor_feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='question_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='question_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='question_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
