# Generated by Django 4.0.4 on 2024-01-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_applications_purpose_alter_applications_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=370),
        ),
    ]

    operations = [
    
        migrations.RunSQL(
            sql="UPDATE api_user SET username = LOWER(username), email = LOWER(email)",
        )
    ]


