# Generated by Django 4.0.4 on 2024-01-07 23:37

from django.db import migrations, models

def update_course_copy(apps, schema_editor):
    # get all the parent track courses and update the child track courses
    Course = apps.get_model('api', 'Course')
    Track = apps.get_model('api', 'Track')

    for track in Track.objects.all():
        parent_track = track.parent
        if parent_track:
            parent_track_courses = parent_track.courses.all()
            for course in parent_track_courses:
                print(track.track_id, course.name)
                try:
                    course_copy = Course.objects.get(track_id=track.track_id, name=course.name)
                    course_copy.access_link = course.access_link
                    course_copy.order = course.order
                    course_copy.requirements = course.requirements
                    course_copy.save()
                except Course.DoesNotExist:
                    print("Course does not exist")
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300),
        ),

        migrations.RunPython(update_course_copy),

    ]


    
    
