# Generated by Django 4.0.4 on 2024-01-21 17:28

from django.db import migrations, models

def update_cohort_duration(apps, schema_editor):
    Cohort = apps.get_model('api', 'Cohort')
    for cohort in Cohort.objects.all():
        cohort.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_name_alter_user_bio'),
    ]

    operations = [
        migrations.RunPython(update_cohort_duration),
    ]
