# Generated by Django 4.0.4 on 2024-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applications',
            name='reason',
            field=models.TextField(),
        ),
    ]
