# Generated by Django 4.0.4 on 2024-02-07 14:01

from django.db import migrations, models

def delete_prod_blockers(apps, schema_editor):
    Blocker = apps.get_model('api', 'Blocker')
    for blocker in Blocker.objects.all():
        blocker.delete()

    # remove the migration record from django_migrations table
    custom_sql = """
    DELETE FROM django_migrations WHERE app='api' AND name='0015_delete_prod_blockers';
    """

    # Execute the SQL query
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(custom_sql)

    # delete this file itself
    import os
    # os.remove(__file__)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_applications_purpose_alter_applications_reason'),
    ]

    operations = [
        migrations.RunPython(delete_prod_blockers),
    ]
