# Generated by Django 4.0.4 on 2024-02-07 14:01

from django.db import migrations, models

def delete_prod_blockers(apps, schema_editor):
    # Blocker = apps.get_model('api', 'Blocker')
    # for blocker in Blocker.objects.all():
    #     blocker.delete()
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_applications_purpose_alter_applications_reason'),
    ]

    operations = [
        migrations.RunPython(delete_prod_blockers),
    ]
