# Generated by Django 4.0.4 on 2024-02-07 14:01

from django.db import migrations, models

def change_email_all_users_to_lowercase(apps, schema_editor):
    User = apps.get_model('api', 'User')
    for user in User.objects.all():
        user.email = user.email.lower()
        user.username = user.username.lower()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_prod_blockers'),
    ]

    operations = [
        migrations.RunPython(change_email_all_users_to_lowercase),
    ]
