# Generated by Django 4.0.4 on 2024-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_change_email_lowercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='purpose',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='applications',
            name='reason',
            field=models.TextField(max_length=1500),
        ),
    ]
