# Generated by Django 4.0.4 on 2025-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_applications_purpose_alter_applications_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
