# Generated by Django 4.0.4 on 2025-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_lga_user_referral_source_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
