name: Deploy Map API
on:
  workflow_dispatch:
  # push:
  #    branches: [ "" ]
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rsync files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-avzr --delete --exclude='.env'"
          SOURCE: "src/apis/"
          EXCLUDE: ".env"
          TARGET: "~/AspirantProgram/src/apis/"

      - name: SSH and Deploy Django App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/AspirantProgram/src/apis/
            pip install -r requirements.txt
            export DJANGO_ENV = "Production"
            export DJANGO_SETTINGS_MODULE=map.settings
            python3 manage.py migrate
            chmod +x restart_gunicorn.sh
            ./restart_gunicorn.sh
