name: Deploy iOS to App Store

on:
  push:
    branches:
      - apple-store-deployment

jobs:
  build-and-deploy:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: src/mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"

      - name: Install dependencies
        run: flutter pub get

      - name: Decode and save Certificate
        env:
          CERTIFICATE_P12: ${{ secrets.APPLE_CERTIFICATE_P12 }}
        run: |
          echo "$CERTIFICATE_P12" | base64 --decode > ios_distribution.p12
          echo "IOS_CERTIFICATE_PATH=$(pwd)/ios_distribution.p12" >> $GITHUB_ENV

      - name: Decode and save Provisioning Profile
        env:
          PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
        run: |
          echo "$PROVISIONING_PROFILE" | base64 --decode > provisioning_profile.mobileprovision
          echo "IOS_PROVISIONING_PROFILE_PATH=$(pwd)/provisioning_profile.mobileprovision" >> $GITHUB_ENV

      - name: Install Certificate
        run: |
          security create-keychain -p "" build.keychain
          security import $IOS_CERTIFICATE_PATH -k build.keychain -P ${{ secrets.APPLE_CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build iOS app
        run: flutter build ipa --release

      - name: Upload to App Store Connect via Fastlane
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
        run: |
          fastlane deliver \
            --ipa "build/ios/ipa/*.ipa" \
            --username "$APPLE_ID" \
            --app_identifier "$BUNDLE_ID" \
            --team_id "${{ secrets.APPLE_TEAM_ID }}" \
            --force \
            --skip_screenshots \
            --skip_metadata
