name: Deploy Study Web App to Production

on:
  push:
    branches:
      - web-app-setup
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sync changes to the production server
      - name: Rsync files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-avzr --delete --exclude='.env.local'"
          EXCLUDE: ".env"
          SOURCE: "src/web_app/"
          TARGET: "~/AspirantProgram/src/web_app/"
          
      # SSH into the server, build, and deploy
      - name: Build and deploy on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/AspirantProgram/src/web_app
            flutter clean
            flutter build web --release
            sudo rm -rf /var/www/flutter-prod/*
            sudo mv build/web/* /var/www/flutter-prod/
