name: Deploy to Test

on:
  push:
    branches:
      - web-app-setup
  pull_request:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4


      # Sync changes to the test server
      - name: Rsync files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-avzr --delete --exclude='.env.local'"
          EXCLUDE: ".env"
          SOURCE: "src/web_app/"
          TARGET: "~/test-aspirant-program/src/web_app/"
          
      # SSH into the server, build, and deploy
      - name: Build and deploy on test server
        env:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
        run: |
          ssh $username@$host << 'EOF'
          cd ~/test-aspirant-program/src/web_app
          flutter clean
          flutter build web --release
          rm -rf /var/www/flutter-test/*
          mv build/web/* /var/www/flutter-test/
          EOF
