name: Deploy Study Web App to Production

on:
  push:
    branches:
      - web-app-deployment-fix
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # Install dependencies and build the app
      - name: Install Flutter Dependencies and Build
        run: |
          cd src/web_app
          flutter pub get
          flutter build web --release

      # Upload build files to the server's temporary directory
      - name: Upload Build Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: src/web_app/build/web/*
          target: /tmp/flutter-build/

      # Move files to the target directory using sudo
      - name: Deploy Files to Target Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo rm -rf /var/www/flutter-prod/*
            sudo mv /tmp/flutter-build/src/web_app/build/web/* /var/www/flutter-prod/
            sudo chown -R www-data:www-data /var/www/flutter-prod/

      # Verify Deployment
      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            ls -l /var/www/flutter-prod/


      # # Sync changes to the production server
      # - name: Rsync files to server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.SERVER_IP }}
      #     REMOTE_USER: ${{ secrets.SERVER_USER }}
      #     REMOTE_PORT: ${{ secrets.SERVER_PORT }}
      #     ARGS: "-avzr --delete --exclude='.env.local'"
      #     EXCLUDE: ".env"
      #     SOURCE: "src/web_app/"
      #     TARGET: "~/AspirantProgram/src/web_app/"
          
      # # SSH into the server, build, and deploy
      # - name: Build and deploy on production server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd ~/AspirantProgram/src/web_app
      #       flutter clean
      #       flutter build web --release
      #       sudo rm -rf /var/www/flutter-prod/*
      #       sudo mv build/web/* /var/www/flutter-prod/
