name: Build and Deploy Android
on:
  workflow_dispatch:
    inputs:
      versionCode:
        description: 'Version Code'
        required: true
        type: string
      versionName:
        description: 'Version Name'
        required: true
        type: string
    # push:
    #   branches: [ "google-play-deployment" ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [18]
        flutter-version: ["3.16.0"]

    defaults:
      run:
        working-directory: src/mobile
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-${{ matrix.flutter-version }}-x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            src/mobile/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get

      - name: Set versionCode and versionName
        run: |
          echo "VERSION_CODE=${{ github.event.inputs.versionCode }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ github.event.inputs.versionName }}" >> $GITHUB_ENV

      - name: Get env from secrets
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ".env"
          fileDir: "./src/mobile"
          encodedString: ${{ secrets.ENV }}
      
      - name: Create key.properties and set values
        working-directory: src/mobile/android
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > key.properties
          echo "keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" >> key.properties
          echo "storeFile=vcn-keystore.jks" >> key.properties

      - name: Convert base64 to binary and create vcn-keystore.jks
        working-directory: src/mobile/android/app
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_FILE }}" | base64 --decode > vcn-keystore.jks

      - name: Build release app bundle
        id: build_app
        working-directory: src/mobile
        run: |
          flutter build appbundle --release --dart-define-from-file=.env
          --build-name=${{ github.event.inputs.versionName }} \
          --build-number=${{ github.event.inputs.versionCode }}

      - name: Upload to Play Store (production)
        uses: r0adkll/upload-google-play@v1.0.18
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
          packageName: com.milsat.aspirant
          releaseFiles: src/mobile/build/app/outputs/bundle/release/app-release.aab
          track: production

      # --build-name "1.3.8" --build-number "16" (Reminder)
