name: iOS App Deployment

on:
  # trigger for automatic testflight beta builds on push to the main branch
  push:
    branches:
      - main
    paths:
      - 'src/mobile/**'
  
  # trigger for automatic appstore deployment on workflow_dispatch
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Application marketing version (e.g., 1.0.0)'
        required: true
        default: '1.0.1'
        type: string
      release_notes_content:
        description: 'Release Notes for App Store (optional)'
        required: false
        default: 'We have made new updates based on your feedback and reviews...'
        type: string
        
concurrency:
  group: ios-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
      runs-on: macos-15
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Select Xcode 16.4
          run: |
            sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
            xcode-select -p
            xcodebuild -version

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.32.1'
            channel: 'stable'
            cache: true

        - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: "3.3.2"
            bundler-cache: true

        - name: Install Ruby dependencies
          working-directory: src/mobile/ios
          run: bundle install --jobs 4 --retry 3

        - name: Install Flutter dependencies
          working-directory: src/mobile
          run: flutter pub get
        
        - name: Install CocoaPods dependencies
          working-directory: src/mobile/ios
          run: |
            pod install --repo-update

        - name: Set up App Store Connect auth file
          working-directory: src/mobile/ios/fastlane
          run: |
            echo '${{ secrets.APP_STORE_CONNECT_JSON_KEY }}' > store.json

        - name: Deploy to Testflight
          if: github.event_name == 'push' || github.event_name == 'pull_request'
          working-directory: src/mobile/ios
          env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
            FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
            CI: true
          run: |
            bundle exec fastlane ios beta

        - name: Deploy to Appstore
          if: github.event_name == 'workflow_dispatch'
          working-directory: src/mobile/ios
          env:
            APP_VERSION_FROM_GH_ACTIONS: ${{ inputs.app_version }}
            RELEASE_NOTES_FROM_GH_ACTIONS: ${{ inputs.release_notes_content }}

            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
            FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
            CI: true
          run: |
            bundle exec fastlane ios release

        - name: Clean up auth file
          if: always()
          run: rm -f src/mobile/ios/fastlane/store.json
        

        