name: Deploy Map API-Test
on:
  workflow_dispatch:
  pull_request:
     branches: [ "main" ]
     paths: ["src/apis/**"]
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Convert Dockerfile.test to Dockerfile
        run: |
          cd /home/runner/work/AspirantProgram/AspirantProgram/src/apis/
          cp Dockerfile.test Dockerfile

      - name: Sync Files to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-rlgoDzvc -i --delete --exclude='.env'"
          SOURCE: "./src/apis/"
          TARGET: "~/test-aspirant-program/src/apis/"

      - name: SSH and Build/Run Dockerized Test App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/test-aspirant-program/src/apis
            echo "Building Docker Image..."
            docker build -t map-api-test:latest .


            echo "Stopping existing test container (if any)..."
            docker stop map-api-test || true
            docker rm map-api-test || true


            echo "Running Docker Container..."
            docker run -d --name map-api-test --env-file .env -p 8001:8001 map-api-test:latest

      - name: Add HTTPS endpoint to PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            checkout your changes to the Test environment URL: [test-aspirant-api.milsat.africa](https://test-aspirant-api.milsat.africa)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: true

      - name: Review PR file(s) with chat-gpt
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.TEMP_OPEN_AI_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          LANGUAGE: English
          
