name: Deploy Test Web Page

on:
  workflow_dispatch:
    
  pull_request:
     branches: [ "main" ]
     paths: ["src/web/**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert Dockerfile.test to Dockerfile
        run: |
          cd /home/runner/work/AspirantProgram/AspirantProgram/src/web/
          cp Dockerfile.test Dockerfile

      - name: Sync Files to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-rlgoDzvc -i --delete --exclude='.env.local'"
          SOURCE: "./src/web/"
          TARGET: "~/test-aspirant-program/src/web/"

      - name: SSH and Build/Run Dockerized Test Web App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/test-aspirant-program/src/web
            echo "Building Docker Image..."
            docker build -t web-app-test:latest .

            echo "Stopping existing test container (if any)..."
            docker stop web-app-test || true
            docker rm web-app-test || true

            echo "Running Docker Container..."
            docker run -d --name web-app-test -p 3002:3002 web-app-test:latest

      - name: Add HTTPS endpoint to PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            checkout your changes to the Test environment URL: [test-aspirant.milsat.africa](https://test-aspirant.milsat.africa)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: true

      - name: Review PR file(s) with chat-gpt
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.TEMP_OPEN_AI_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          LANGUAGE: English
