name: Deploy Map API-Test
on:
  pull_request:
     branches: [ "main" ]
     paths: ["src/apis/**"]
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rsync files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          ARGS: "-avzr --delete --exclude='.env'"
          SOURCE: "src/apis/"
          EXCLUDE: ".env"
          TARGET: "~/test-aspirant-program/src/apis/"

      - name: SSH and Deploy Django App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/test-aspirant-program/src/apis/
            pip install -r requirements.txt
            export DJANGO_ENV = "Test"
            export DJANGO_SETTINGS_MODULE=map.settings_test
            python3 manage.py migrate
            chmod +x test_restart_gunicorn.sh
            ./test_restart_gunicorn.sh

      - name: Add HTTPS endpoint to PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            checkout your changes to the Test environment URL: [test-aspirant-api.milsat.africa](https://test-aspirant-api.milsat.africa)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: true

      - name: Review PR file(s) with chat-gpt
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.TEMP_OPEN_AI_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          LANGUAGE: English
